# Sonoff 4CH

substitutions:
  devicename: "basic-8266"
  friendly_devicename: "basic-8266"

  mac_suffix: "true"

  wifi_domainname: ".smarthome"

  #Protect the Fallback AP
  wifi_fallback_ap_pw: ""

  #Protect the OTA Access to your Device
  ota_password: ""

esp8266:
  board: esp01_1m

esphome:
  project:
    name: "diekruecke.basic_8266"
    version: "0.1"

api:
  
packages:
  esphome_basis: !include includes/esphome_config.yaml


dashboard_import:
  package_import_url: github://diekruecke/esphome_templates/basic-8266.yaml@main
  import_full_config: false
