esphome:
  name: ${devicename}
  friendly_name: "${friendly_devicename}"
  build_path: ./build/${devicename}

  name_add_mac_suffix: ${mac_suffix}

  comment: "www.diekruecke.de"
  project:
    name: "diekruecke.kruecketemplate_vtec_a60"
    version: "0.1"

esp8266:
  board: esp01_1m
  restore_from_flash: true

web_server:
  port: 80
  js_include: "webinterface/www.js"
  js_url: ""
  version: 2

logger:

ota:
  password: ${ota_password}

wifi:
  domain: ${wifi_domainname}
  ap:
    ssid: ${devicename} Fallback
    password: ${wifi_fallback_ap_pw}

improv_serial:
  next_url: http://{{ip_address}}.smarthome

captive_portal: