
# Enable Home Assistant API
api:
  encryption:
    key: ${api_key}
  
# HA Status Anzeige
binary_sensor:
  - platform: status
    name: ${friendly_devicename} Status

text_sensor:
# HA ESPHomeVersions Anzeige
  - platform: version
    name: ${friendly_devicename} ESPHome Version
    hide_timestamp: true
  
# HA WifiInfo Anzeige
  - platform: wifi_info
    ip_address:
      name: ${friendly_devicename} IP Address
    ssid:
      name: ${friendly_devicename} Connected SSID
    mac_address:
      name: ${friendly_devicename} Mac Wifi Address

sensor:
  - platform: uptime
    name: ${friendly_devicename} Uptime Sensor

  # Wifi Signalstärke in dB
  - platform: wifi_signal
    name: ${friendly_devicename} WiFi Signal dB
    id: wifi_signal_db
    update_interval: 120s
    entity_category: "diagnostic"

  # Wifi Signalstärke in %
  - platform: copy
    source_id: wifi_signal_db
    name: ${friendly_devicename} WiFi Signal Prozent
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

switch:
  - platform: restart
    name: ${friendly_devicename} Restart
  - platform: safe_mode
    name: ${friendly_devicename} Restart into Safe Mode
    disabled_by_default: true
  - platform: factory_reset
    name: ${friendly_devicename} Reset to Factory Settings
    disabled_by_default: true