# V-TAC LED A60 BULB

substitutions:
  devicename: "vtac-a60"
  friendly_devicename: "V-TAC A60"

  mac_suffix: "true"

  wifi_domainname: ".smarthome"

  #Protect the Fallback AP
  wifi_fallback_ap_pw: ""

  #Protect the OTA Access to your Device
  ota_password: ""

packages:
  esphome_basis: !include esphome_basis.yaml
  homeassistant: !include homeassistant.yaml
  vtac60: !include vtac60.yaml

dashboard_import:
  package_import_url: github://diekruecke/kruecketemplate_vtec_a60/main_file.yaml@main
  import_full_config: false
