# V-TAC LED A60 BULB

substitutions:
  devicename: "vtac-a60"
  friendly_devicename: "V-TAC LED A60 BLUB"
  device_comment: "www.diekruecke.de"

  project_name: "diekruecke.esphome_template_vtac60"
  project_version: "0.1"

  mac_suffix: "true"

  #Add your WIFI Credentials
  wifi_ssid: "12341234"
  wifi_pw: "12341234"
  wifi_domainname: ".local"
  wifi_fallback_ap_pw: ""

  #protect the OTA Access to your Device
  ota_password: ""

  #replace this key -> https://esphome.io/components/api.html?highlight=api+key#configuration-variables
  api_key: "DaPSLoUXvbnPYBfVl30tdnz8uRgHCIQJIcPr6mJajPA="

packages:
  esphome_basis: !include esphome_basis.yaml
  homeassistant: !include homeassistant.yaml
  vtac60: !include vtac60.yaml

esp8266:
  board: esp01_1m
  restore_from_flash: true

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://diekruecke/esphome_template_vtac60/main_file.yaml@main
