# POW Origin 16A

substitutions:
  devicename: "sonoff-pow-origin-16a"
  friendly_devicename: "Sonoff POW Origin 16A"

  mac_suffix: "true"

  wifi_domainname: ".smarthome"

  #Protect the Fallback AP
  wifi_fallback_ap_pw: ""
  #wifi_fallback_ap_pw: !secret esphome_fallback_ap_pw

  #Protect the OTA Access to your Device
  ota_password: ""
  #ota_password: !secret esphome_ota_password

packages:
  remote_package:
    url: https://github.com/diekruecke/esphome_templates
    ref: main
    refresh: 60s
    files:
      - includes/esphome_config.yaml
      - includes/homeassistant_config.yaml
      - includes/geräte/strom/pow_origin_16a.yaml

dashboard_import:
  package_import_url: github://diekruecke/esphome_templates/pow-origin-16a.yaml@main
  import_full_config: false
