# POW Origin 16A

substitutions:
  devicename: "pow-origin-16a"
  friendly_devicename: "POW Origin 16A"

  mac_suffix: "true"

  wifi_domainname: ".smarthome"

  #Protect the Fallback AP
  wifi_fallback_ap_pw: ""
  #wifi_fallback_ap_pw: !secret wifi_fallback_ap_pw

  #Protect the OTA Access to your Device
  ota_password: ""
  #ota_password: !secret ota_password

packages:
  esphome_basis: !include includes/esphome_config.yaml
  homeassistant: !include includes/homeassistant_config.yaml
  device_details: !include includes/geräte/strom/pow_origin_16a.yaml

dashboard_import:
  package_import_url: github://diekruecke/esphome_templates/pow-origin-16a.yaml@main
  import_full_config: false
