# These substitutions allow the end user to override certain values
substitutions:
  name: "project-template"

esphome:
  name: "${name}"
  name_add_mac_suffix: true

  project:
    name: diekruecke.test_template
    version: "1.0"

esp8266:
  board: d1_mini

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:

dashboard_import:
  package_import_url: github://diekruecke/kruecketemplate_vtec_a60/project-template-esp8266.yaml@main
  import_full_config: false
wifi:
  # Set up a wifi access point using the device name above
  ap:
    password: "12345678"

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

improv_serial:
