# Sonoff POW316 Origin
# sonoff-powr316-origin

substitutions:
  devicename: "sonoff-powr316-origin"
  friendly_devicename: "Sonoff POW316 Origin"

  mac_suffix: "true"

  # Your WifiData
  wifi: "YourRandomWifi"
  #wifi: !secret krueckesmarthomewifi

  wifi_pw: "YourRandomWifiPassword"
  #wifi_pw: !secret krueckesmarthomewifi_pw

  wifi_domainname: ".smarthome"

  #Protect the Fallback AP
  wifi_fallback_ap_pw: ""
  #wifi_fallback_ap_pw: !secret esphome_fallback_ap_pw

  #Protect the OTA Access to your Device
  ota_password: ""
  #ota_password: !secret esphome_ota_password

  #Publish the Relay to Homeassistant
  publish_relay: "false"

packages:
  remote_package:
    url: https://github.com/diekruecke/esphome_templates
    ref: main
    refresh: 60s
    files:
      - includes/esphome_config.yaml
      - includes/homeassistant_config.yaml
      - includes/geräte/strom/sonoff_powr316_origin.yaml

dashboard_import:
  package_import_url: github://diekruecke/esphome_templates/sonoff-powr316-origin.yaml@main
  import_full_config: false
