# V-TAC LED A60 BULB
# VT-5113 SKU-2752
# RGB + 2700K-6400k
# 11W - 1055lm - E27

substitutions:
  devicename: "vtac-a60"
  friendly_devicename: "V-TAC A60 LED Bulb"

  mac_suffix: "true"

  wifi_domainname: ".smarthome"

  #Protect the Fallback AP
  wifi_fallback_ap_pw: ""

  #Protect the OTA Access to your Device
  ota_password: ""

packages:
  esphome_basis: !include includes/esphome_config.yaml
  homeassistant: !include includes/homeassistant_config.yaml
  vtac-a60: !include includes/geräte/licht/vtac_a60.yaml

dashboard_import:
  package_import_url: github://diekruecke/esphome_templates/vtac-a60.yaml@main
  import_full_config: false
