esphome:
  project:
    name: "diekruecke.pow_origin_16a"
    version: "0.1"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

esp32_improv:
  authorizer: none

uart:
  rx_pin: GPIO16
  baud_rate: 4800

sensor:
  - platform: internal_temperature
    name: ${friendly_devicename} Int. Temperature
  - platform: cse7766
    update_interval: 10s
    current:
      name: ${friendly_devicename} Current
      id: a_sensor
    voltage:
      name: ${friendly_devicename} Voltage
      id: v_sensor
    power:
      name: ${friendly_devicename} Power
      id: w_sensor
      on_value_range:
        - above: 4.0
          then:
            - light.turn_on: switch_led
        - below: 3.0
          then:
            - light.turn_off: switch_led
    energy:
      name: ${friendly_devicename} Energy
      id: wh_sensor

output:
  - platform: ledc
    id: led
    pin:
      number: GPIO18
      inverted: True

light:
  - platform: monochromatic
    id: switch_led
    output: led
    internal: True
  - platform: status_led
    id: wifi_status_led
    internal: True
    pin:
      number: GPIO05
      inverted: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${friendly_devicename} - Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "${friendly_devicename} - Relay Switch"
    pin: GPIO13
    id: relay

status_led:
  pin:
    number: GPIO16
    inverted: yes