esphome:
  project:
    name: "diekruecke.sonoff-powr316-origin"
    version: "0.3"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

uart:
  rx_pin: GPIO16
  baud_rate: 4800

sensor:
  - platform: cse7766
    update_interval: 10s
    current:
      name: Current
      id: a_sensor
    voltage:
      name: Voltage
      id: v_sensor
    power:
      name: Power
      id: w_sensor
    energy:
      name: Energy
      id: wh_sensor

output:
  - platform: ledc
    id: led
    pin:
      number: GPIO18
      inverted: True

light:
  - platform: monochromatic
    id: switch_led
    output: led
    internal: True
  - platform: status_led
    id: wifi_status_led
    internal: True
    pin:
      number: GPIO05
      inverted: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button"
    internal: true
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO13
    id: relay
    internal: ${publish_relay}
    restore_mode: ALWAYS_ON
    on_turn_on:
      - light.turn_on: switch_led
    on_turn_off:
      - light.turn_off: switch_led

status_led:
  pin:
    number: GPIO16
    inverted: yes