esphome:
  name: ${devicename}
  friendly_name: "${friendly_devicename}"

  name_add_mac_suffix: ${mac_suffix}

  comment: "https://github.com/diekruecke/esphome_templates"

web_server:
  port: 80
  js_url: "https://raw.githubusercontent.com/diekruecke/esphome_templates/main/includes/webinterface/www.js"
  version: 2
  include_internal: true
  local: true

logger:

ota:
  password: ${ota_password}

wifi:
  ssid: "${wifi}"
  password: "${wifi_pw}"
  domain: "${wifi_domainname}"
  ap:
    ssid: ${devicename} Fallback
    password: ${wifi_fallback_ap_pw}

improv_serial:
  next_url: http://{{ip_address}}.${wifi_domainname}

captive_portal: