
# Enable Home Assistant API
api:
  
# HA Status Anzeige
binary_sensor:
  - platform: status
    name: Status

text_sensor:
# HA ESPHomeVersions Anzeige
  - platform: version
    name: ESPHome Version
    hide_timestamp: true
  
# HA WifiInfo Anzeige
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    mac_address:
      name: Mac Wifi Address

sensor:
  - platform: uptime
    name: Uptime Sensor

switch:
  - platform: restart
    name: Restart
  - platform: safe_mode
    name: Restart into Safe Mode
    disabled_by_default: true
  - platform: factory_reset
    name: Reset to Factory Settings
    disabled_by_default: true