
# Enable Home Assistant API
api:
  
# HA Status Anzeige
binary_sensor:
  - platform: status
    name: HA Verbindungstatus

text_sensor:
# HA ESPHomeVersions Anzeige
  - platform: version
    name: ESPHome Version
    hide_timestamp: true
  
# HA WifiInfo Anzeige
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID

sensor:
  - platform: uptime
    name: Uptime Sensor
    update_interval: 1min

button:
  - platform: restart
    name: Restart
    disabled_by_default: true
  - platform: factory_reset
    name: Reset to Factory Settings
    disabled_by_default: true